### ISSUE TITLE
Which opencv version do u use?

### ISSUE THREAD

**Issue by DeepDuke** [goldleaf3i/declutter-reconstruct#2]
Hi, may I ask what exact version of opencv do u use in this project? I met something wrong like this:
```python3
Traceback (most recent call last):
  File "runMe.py", line 231, in <module>
    main()
  File "runMe.py", line 86, in main
    start_main(action, parameters_object, paths)
  File "runMe.py", line 225, in start_main
    minibatch.start_main(par, parameters_object, paths)
  File "/home/spacex/melodic_workspace/declutter-reconstruct/code/minibatch.py", line 170, in start_main
    (contours, vertices) = lay.external_contour(img_cont)
  File "/home/spacex/melodic_workspace/declutter-reconstruct/code/util/layout.py", line 76, in external_contour
    contours.pop(0)
AttributeError: 'tuple' object has no attribute 'pop'
```
The version of opencv-python I'm using is `3.4.17.63`. Thank you!

**Comment by goldleaf3i** [comment]
Sorry, I missed your comment!

We are migrating to a new repo and we are integrating it with newer version of openCV, as they've changed a bit some of the methods we use.

Check here:
https://github.com/aislabunimi/ROSE2
There should be indications on the method of opencv to use in the layout.py code.
